import Link from 'next/link';

interface Props {
  params: Promise<{ tokenId: string }>;
}

export default async function VerifyPropertyPage({ params }: Props) {
  const { tokenId } = await params;

  return (
    <div className="max-w-lg mx-auto px-6 py-16 page-enter text-center">
      {/* Logo */}
      <div className="relative mb-8 inline-block">
        <div className="w-20 h-20 rounded-xl bg-gradient-to-br from-[#B09B71] via-[var(--brass-deep)] to-[#8A7A5A] flex items-center justify-center shadow-2xl mx-auto">
          <span className="text-4xl font-normal text-[var(--text-heading)]">S</span>
        </div>
      </div>

      <h1 className="text-3xl sm:text-4xl font-medium gradient-text mb-2">Property Verified</h1>
      <p className="text-[var(--text-muted)] text-sm mb-8">
        This QR code was generated by SuvrenHOA — a blockchain-powered HOA governance platform.
      </p>

      {/* Property Info Card */}
      <div className="glass-card rounded-xl p-8 text-left mb-6">
        <p className="text-xs tracking-widest uppercase text-[var(--text-disabled)] mb-4">Property NFT</p>

        <div className="space-y-4">
          <div>
            <p className="text-xs text-[var(--text-disabled)] mb-1">Token ID</p>
            <p className="text-2xl font-normal text-[#B09B71]">#{tokenId}</p>
          </div>

          <div className="h-px bg-[rgba(245,240,232,0.05)]" />

          <div>
            <p className="text-xs text-[var(--text-disabled)] mb-1">Network</p>
            <p className="text-sm font-medium text-[var(--text-body)]">Base Blockchain (Ethereum L2)</p>
          </div>

          <div>
            <p className="text-xs text-[var(--text-disabled)] mb-1">Community</p>
            <p className="text-sm font-medium text-[var(--text-body)]">Faircroft HOA</p>
          </div>

          <div>
            <p className="text-xs text-[var(--text-disabled)] mb-1">Verification URL</p>
            <p className="text-xs font-mono text-[var(--text-disabled)] break-all">
              https://hoa.suvren.co/verify/{tokenId}
            </p>
          </div>
        </div>
      </div>

      {/* Trust badge */}
      <div className="glass-card rounded-xl p-5 mb-8 border border-[rgba(176,155,113,0.20)]">
        <div className="flex items-start gap-3 text-left">
          <span className="text-xl"></span>
          <div>
            <p className="text-sm font-medium text-[#D4C4A0] mb-1">On-Chain Transparency</p>
            <p className="text-xs text-[var(--text-muted)] leading-relaxed">
              This property is recorded as an NFT on the Base blockchain.
              Ownership, voting rights, and dues history are permanently immutable.
            </p>
          </div>
        </div>
      </div>

      <Link
        href="/"
        className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#B09B71] hover:bg-[#D4C4A0] text-[var(--surface-2)] text-sm font-medium transition-all"
      >
         Visit SuvrenHOA
      </Link>
    </div>
  );
}
