import Link from 'next/link';

interface Props {
  params: Promise<{ tokenId: string }>;
}

export default async function VerifyPropertyPage({ params }: Props) {
  const { tokenId } = await params;

  return (
    <div className="max-w-lg mx-auto px-6 py-16 page-enter text-center">
      {/* Logo */}
      <div className="relative mb-8 inline-block">
        <div className="w-20 h-20 rounded-3xl bg-gradient-to-br from-[#c9a96e] via-[#b8942e] to-[#8a6820] flex items-center justify-center shadow-2xl mx-auto">
          <span className="text-4xl font-black text-white">S</span>
        </div>
      </div>

      <h1 className="text-3xl font-extrabold mb-2 gradient-text">Property Verified</h1>
      <p className="text-gray-400 text-sm mb-8">
        This QR code was generated by SuvrenHOA — a blockchain-powered HOA governance platform.
      </p>

      {/* Property Info Card */}
      <div className="glass-card rounded-2xl p-8 text-left border-l-2 border-l-[#c9a96e]/50 mb-6">
        <p className="text-xs text-gray-500 font-semibold uppercase tracking-widest mb-4">Property NFT</p>

        <div className="space-y-4">
          <div>
            <p className="text-xs text-gray-600 mb-1">Token ID</p>
            <p className="text-2xl font-extrabold text-[#c9a96e]">#{tokenId}</p>
          </div>

          <div className="h-px bg-white/5" />

          <div>
            <p className="text-xs text-gray-600 mb-1">Network</p>
            <p className="text-sm font-medium text-gray-300">Base Blockchain (Ethereum L2)</p>
          </div>

          <div>
            <p className="text-xs text-gray-600 mb-1">Community</p>
            <p className="text-sm font-medium text-gray-300">Faircroft HOA</p>
          </div>

          <div>
            <p className="text-xs text-gray-600 mb-1">Verification URL</p>
            <p className="text-xs font-mono text-gray-500 break-all">
              https://hoa.suvren.co/verify/{tokenId}
            </p>
          </div>
        </div>
      </div>

      {/* Trust badge */}
      <div className="glass-card rounded-xl p-5 mb-8 border border-[#c9a96e]/20">
        <div className="flex items-start gap-3 text-left">
          <span className="text-xl">🔗</span>
          <div>
            <p className="text-sm font-semibold text-[#e8d5a3] mb-1">On-Chain Transparency</p>
            <p className="text-xs text-gray-400 leading-relaxed">
              This property is recorded as an NFT on the Base blockchain.
              Ownership, voting rights, and dues history are permanently immutable.
            </p>
          </div>
        </div>
      </div>

      <Link
        href="/"
        className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#c9a96e] hover:bg-[#e8d5a3] text-[#1a1a1a] text-sm font-bold transition-all"
      >
        🏠 Visit SuvrenHOA
      </Link>
    </div>
  );
}
